[build]
  command = "node build-manifests.js"
  publish = "."

[[redirects]]
  from = "/doom"
  to = "/doom.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
