[build]
  command = "node build-manifests.js"
  publish = "."

[[redirects]]
  from = "/roms/*"
  to = "/404"
  status = 404
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
