[build]
  command = "node build-manifests.js"
  publish = "."

[[redirects]]
  from = "/dkc-rom"
  to = "https://archive.org/download/donkey-kong-country-usa_202502/Donkey%20Kong%20Country%20%28USA%29.sfc"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
